# -*- mode: dockerfile -*-

#
# This is the HAProxy router for OpenShift Origin.
#
# The standard name for this image is openshift/origin-haproxy-router
#
FROM quay.io/openshift/origin-haproxy-router:4.8 as openshift-router
USER 0

FROM localhost/haproxy-builder-bz2044682
# Run as USER 0 required for setcap
USER 0
RUN  mkdir -p /var/lib/haproxy/router/{certs,cacerts,whitelists} && \
     mkdir -p /var/lib/haproxy/{conf/.tmp,run,bin,log} && \
    touch /var/lib/haproxy/conf/{{os_http_be,os_edge_reencrypt_be,os_tcp_be,os_sni_passthrough,os_route_http_redirect,cert_config,os_wildcard_domain}.map,haproxy.config}

COPY --from=openshift-router /usr/bin/openshift-router /usr/bin/
COPY --from=openshift-router /var/lib/haproxy /var/lib/haproxy

RUN chown -R :0 /var/lib/haproxy && \
    chmod -R g+w /var/lib/haproxy

WORKDIR /src
COPY . /src
RUN rm -rf etc-pki-entitlement rhsm.conf rhsm-ca
RUN make clean
RUN rm -f haproxy
RUN make -f Makefile -j $(nproc) \
     V=1 \
     CPU="generic" \
     TARGET="linux-glibc" \
     USE_REGPARM=1 \
     USE_OPENSSL=1 \
     USE_PCRE=1 \
     USE_ZLIB=1 \
     USE_CRYPT_H=1 \
     USE_LINUX_TPROXY=1 \
     USE_GETADDRINFO=1 \
     DEBUG="-DDEBUG_FULL"
RUN ls -l haproxy
RUN cp ./haproxy /usr/sbin/haproxy
RUN setcap 'cap_net_bind_service=ep' /usr/sbin/haproxy
RUN make clean

USER 1001
EXPOSE 80 443
WORKDIR /var/lib/haproxy/conf
ENV TEMPLATE_FILE=/var/lib/haproxy/conf/haproxy-config.template \
    RELOAD_SCRIPT=/var/lib/haproxy/reload-haproxy
ENTRYPOINT ["/usr/bin/openshift-router", "--v=2"]
