---
# Nix does not work with selinux enabled yet!
# see https://github.com/NixOS/nix/issues/2374
- name: Disable SELinux
  hosts: all
  tasks:
  - name: set selinux disabled
    ansible.posix.selinux:
      state: disabled
