---
- name: configure sshd options
  hosts: all
  tasks:
  - name: Check for StreamLocalBindUnlink
    lineinfile:
      state: absent
      path: "/etc/ssh/sshd_config"
      regexp: "^StreamLocalBindUnlink yes"
    check_mode: true
    changed_when: false
    register: check
  - name: Add StreamLocalBindUnlink setting
    lineinfile:
      state: present
      path: "/etc/ssh/sshd_config"
      line: "StreamLocalBindUnlink yes"
    when: check.found == 0
  - name: Restart sshd
    ansible.builtin.systemd:
      name: sshd
      state: restarted
    when: check.found == 0
