---
- name: configure network kernel parameters
  hosts: all
  tasks:
  - name: configure net.core.somaxconn
    ansible.posix.sysctl:
      name: net.core.somaxconn
      value: '4096'
      sysctl_set: yes
      state: present
      reload: yes
  - name: configure net.ipv4.tcp_max_syn_backlog
    ansible.posix.sysctl:
      name: net.ipv4.tcp_max_syn_backlog
      value: '8192'
      sysctl_set: yes
      state: present
      reload: yes
  - name: configure net.ipv4.ip_local_port_range
    ansible.posix.sysctl:
      name: net.ipv4.ip_local_port_range
      value: '2000 65535'
      sysctl_set: yes
      state: present
      reload: yes
