---
- name: install packages
  gather_facts: false
  hosts: all
  tasks:
  - name: install packages
    dnf:
      name: strace, wget, bind-utils, golang, rsync, lsof, tar, zsh, glibc-minimal-langpack, glibc-all-langpacks, util-linux-user
      
