---
- name: add user aim
  hosts: all
  tasks:
  - name: Install packages required by user aim login
    dnf:
      name: git, zsh, util-linux-user, make
      state: present
  - name: add group aim
    ansible.builtin.group:
      name: aim
      gid: 1000
      state: present
  - name: add user aim
    ansible.builtin.user:
      name: aim
      shell: /bin/zsh
      uid: 1000
      groups: aim,adm,systemd-journal,wheel
      state: present
  - name: create dummy .zshrc
    file:
      path: /home/aim/.zshrc
      state: touch
      mode: 0644
      owner: aim
  - name: Add user to sudo
    lineinfile:
      path: /etc/sudoers.d/aim
      line: 'aim ALL=(ALL) NOPASSWD: ALL'
      state: present
      mode: 0440
      create: yes
      validate: 'visudo -cf %s'
  - name: Set authorized keys taken from url
    ansible.posix.authorized_key:
      user: aim
      state: present
      key: https://github.com/frobware.keys
